const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const base=process.env.BASE_URL||'http://127.0.0.1:8774/path-planning-visualizer/';const baseline=process.env.BASELINE_URL;
const report={checks:[],errors:[],resources:[],performance:[],algorithmComparisons:0};
function ok(name,value){assert.ok(value,name);report.checks.push(name);console.log('PASS',name)}
async function open(browser,options={}){const p=await browser.newPage(options);p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});p.on('response',r=>{if(r.status()>=400)report.resources.push(r.url())});await p.goto(base);await p.waitForFunction(()=>window.atlas3D?.rover);await p.waitForTimeout(50);return p;}
async function point(p,r,c){return p.evaluate(({r,c})=>{const v=atlas3D.rover.position.clone().set(c-18.5,.12,r-11.5).project(atlas3D.camera);const b=document.querySelector('#sceneHost canvas').getBoundingClientRect();return {x:b.x+(v.x+1)*b.width/2,y:b.y+(1-v.y)*b.height/2}}, {r,c});}
async function cellClick(p,r,c,button='left'){const q=await point(p,r,c);await p.mouse.click(q.x,q.y,{button});}
async function idle(p,name){await p.waitForTimeout(80);const before=await p.evaluate(()=>atlas3D.renderer.info.render.frame);await p.waitForTimeout(140);ok(name,before===await p.evaluate(()=>atlas3D.renderer.info.render.frame));}
(async()=>{const b=await chromium.launch({executablePath:process.env.BROWSER_PATH,headless:true});report.browser=await b.version();try{
const p=await open(b,{viewport:{width:1440,height:1000}});
ok('Blender GLB loaded with all four wheel pivots',await p.evaluate(()=>atlas3D.wheels.map(w=>w.name).join(',')==='Wheel_LF,Wheel_LB,Wheel_RF,Wheel_RB'));
report.model=await p.evaluate(()=>{const meshes=[];atlas3D.rover.traverse(o=>{if(o.isMesh)meshes.push(o.name)});return {meshes:meshes.length,wheels:atlas3D.wheels.map(w=>({name:w.name,position:w.position.toArray(),rotation:w.rotation.toArray()}))}});
await idle(p,'idle 3D does not continuously submit frames');
const initial=await p.evaluate(()=>atlas3D.camera.position.toArray());const bb=await p.locator('#sceneHost').boundingBox();await p.mouse.move(bb.x+bb.width*.5,bb.y+bb.height*.5);await p.mouse.down();await p.mouse.move(bb.x+bb.width*.65,bb.y+bb.height*.6,{steps:8});await p.mouse.up();ok('orbit drag rotates camera',JSON.stringify(initial)!==JSON.stringify(await p.evaluate(()=>atlas3D.camera.position.toArray())));
await p.click('#zoomIn');ok('zoom control changes frustum',await p.evaluate(()=>Math.abs(atlas3D.camera.top)<17));await p.click('#overviewBtn');await p.click('#topBtn');await p.click('#editBtn');await p.waitForTimeout(50);
await cellClick(p,3,3);ok('3D paint adds wall at raycast cell',await p.evaluate(()=>walls.has('3,3')));
await p.selectOption('#brush','rough');await cellClick(p,4,3);ok('3D cost-4 brush',await p.evaluate(()=>terrain.get('4,3')===4));
await p.selectOption('#brush','heavy');await cellClick(p,5,3);ok('3D cost-8 brush',await p.evaluate(()=>terrain.get('5,3')===8));
await cellClick(p,3,3,'right');ok('3D right-click erases',await p.evaluate(()=>!walls.has('3,3')));
let a=await point(p,12,5),z=await point(p,10,4);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(z.x,z.y,{steps:5});await p.mouse.up();ok('START can be dragged in 3D',await p.evaluate(()=>start.r===10&&start.c===4));
a=await point(p,12,32);z=await point(p,11,33);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(z.x,z.y,{steps:5});await p.mouse.up();ok('GOAL can be dragged in 3D',await p.evaluate(()=>goal.r===11&&goal.c===33));
await p.click('#view2d');await p.selectOption('#brush','wall');await p.locator('.cell[data-r="1"][data-c="1"]').click();ok('2D editing updates same model',await p.evaluate(()=>walls.has('1,1')));await idle(p,'2D view suspends 3D renderer');await p.click('#view3d');
for(const quality of ['low','high','auto']){await p.selectOption('#qualitySelect',quality);ok(`${quality} quality setting`,await p.evaluate(q=>atlas3D.renderer.shadowMap.enabled===(q!=='low')&&atlas3D.renderer.getPixelRatio()===Math.min(devicePixelRatio,q==='low'?1:q==='high'?2:1.5),quality));}
await p.click('#resetBtn');await p.click('#orbitBtn');await p.click('#overviewBtn');
await p.locator('#speed').fill('1');await p.click('#runBtn');await p.waitForTimeout(220);await p.click('#pauseBtn');await p.waitForTimeout(80);const visited=await p.evaluate(()=>visitedCells.size);await p.waitForTimeout(200);ok('search pause freezes exploration',visited===await p.evaluate(()=>visitedCells.size));ok('painting and map controls locked while searching',await p.locator('#brush').isDisabled());await p.click('#stopBtn');ok('stop cancels and restores controls',await p.evaluate(()=>!isRunning&&!runBtn.disabled));
for(const algorithm of ['astar','dijkstra','greedy']){await p.selectOption('#algorithm',algorithm);await p.locator('#speed').fill('5');await p.click('#runBtn');await p.waitForFunction(()=>!isRunning);ok(`${algorithm} search completes`,Number(await p.locator('#statCost').textContent())>0);ok(`${algorithm} has playable rover route`,await p.evaluate(()=>latestPath.length>0&&atlas3D.moving));await p.click('#clearPathBtn');}
await p.selectOption('#algorithm','astar');await p.click('#runBtn');await p.waitForFunction(()=>!isRunning);await p.click('#followBtn');const first=await p.evaluate(()=>({position:atlas3D.rover.position.toArray(),wheels:atlas3D.wheels.map(w=>w.rotation.x)}));await p.waitForTimeout(350);ok('rover and wheel pivots animate on the path',JSON.stringify(first)!==JSON.stringify(await p.evaluate(()=>({position:atlas3D.rover.position.toArray(),wheels:atlas3D.wheels.map(w=>w.rotation.x)}))));
await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});await idle(p,'hidden document suspends GPU frames');await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))});
await p.waitForFunction(()=>!atlas3D.moving,null,{timeout:15000});ok('rover arrives at GOAL',await p.evaluate(()=>Math.abs(atlas3D.rover.position.x-(goal.c-18.5))<.001&&Math.abs(atlas3D.rover.position.z-(goal.r-11.5))<.001));await idle(p,'completed replay returns to idle');await p.click('#replayBtn');ok('rover replay restarts',await p.evaluate(()=>atlas3D.moving));await p.click('#clearPathBtn');
await p.click('#overviewBtn');for(const [width,height]of [[360,800],[768,1024],[844,390],[1920,1080]]){await p.setViewportSize({width,height});await p.waitForTimeout(60);ok(`responsive ${width}x${height}`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('#sceneHost canvas').width>0));}
// The search implementation is compared with the original, including exact exploration order.
if(baseline){const old=await b.newPage();await old.goto(baseline);
const cases=async page=>page.evaluate(()=>{const output=[];for(let seed=1;seed<=8;seed++)for(const diagonal of [false,true]){let n=seed;const rand=()=>((n=(n*1664525+1013904223)>>>0)/4294967296);start={r:2,c:2};goal={r:21,c:35};walls.clear();terrain.clear();visitedCells.clear();pathCells.clear();for(let r=0;r<24;r++)for(let c=0;c<38;c++){if((r===2&&c===2)||(r===21&&c===35))continue;const x=rand();if(x<.19)walls.add(key(r,c));else if(x<.31)terrain.set(key(r,c),4);else if(x<.37)terrain.set(key(r,c),8);}diagonalToggle.checked=diagonal;for(const type of ['astar','dijkstra','greedy'])output.push({seed,diagonal,type,...runSearch(type)});}return output});
const before=await cases(old),after=await cases(p);assert.deepEqual(after,before);report.algorithmComparisons=after.length;ok('48 seeded searches exactly match original cost, path and exploration order',true);await old.close();}
const math=await p.evaluate(()=>{walls.clear();terrain.clear();start={r:2,c:2};goal={r:4,c:4};diagonalToggle.checked=true;const diagonal=runSearch('astar').cost;walls.add('2,3');walls.add('3,2');const corner=runSearch('astar').cost;walls.clear();start={r:12,c:5};goal={r:12,c:10};diagonalToggle.checked=false;for(let c=6;c<10;c++)terrain.set(key(12,c),8);const weighted=runSearch('astar').cost;for(let r=0;r<24;r++)walls.add(key(r,7));const impossible=runSearch('astar');return {diagonal,corner,weighted,found:impossible.found}});
ok('diagonal metric uses sqrt(2)',Math.abs(math.diagonal-2*Math.SQRT2)<1e-9);ok('blocked corners cannot be cut',math.corner>math.diagonal);ok('weighted search takes cheaper detour',math.weighted===7);ok('unreachable map reports no path',math.found===false);
await p.evaluate(()=>{renderGrid();speedEl.value='5'});await p.click('#runBtn');await p.waitForFunction(()=>!isRunning);ok('no-path UI recovers and disables rover replay',await p.locator('#statusBox').textContent().then(t=>t.includes('No path'))&&await p.locator('#replayBtn').isDisabled());await p.click('#resetBtn');
const memory=await p.evaluate(()=>{atlas3D.renderer.render(atlas3D.scene,atlas3D.camera);const before={...atlas3D.renderer.info.memory};for(let i=0;i<20;i++){resetDemo();const result=runSearch('astar');result.path.forEach(p=>pathCells.add(key(p.r,p.c)));renderGrid();atlas3D.play(result.path);clearSearchVisualization();atlas3D.renderer.render(atlas3D.scene,atlas3D.camera)}return {before,after:{...atlas3D.renderer.info.memory}}});report.memory=memory;ok('20 search/reset cycles keep GPU resource counts stable',JSON.stringify(memory.before)===JSON.stringify(memory.after));
await p.close();
const mobile=await open(b,{viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});ok('mobile run button visible without scrolling',await mobile.locator('#runBtn').evaluate(e=>e.getBoundingClientRect().bottom<innerHeight));await mobile.click('#topBtn');await mobile.click('#editBtn');await mobile.waitForTimeout(60);a=await point(mobile,2,2);z=await point(mobile,3,2);const cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[z]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});ok('touch paints 3D terrain',await mobile.evaluate(()=>walls.has('2,2')&&walls.has('3,2')));await mobile.close();
const reduced=await open(b,{reducedMotion:'reduce'});await reduced.locator('#speed').fill('5');await reduced.click('#runBtn');await reduced.waitForFunction(()=>!isRunning);ok('reduced motion presents route without automatic rover traversal',await reduced.evaluate(()=>!atlas3D.moving&&latestPath.length>0));await reduced.close();
const fallback=await b.newPage();await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/.test(type)?null:original.call(this,type,...args)}});await fallback.goto(base);await fallback.waitForSelector('#grid:visible');await fallback.locator('#speed').fill('5');await fallback.click('#runBtn');await fallback.waitForFunction(()=>!isRunning);ok('WebGL unavailable: 2D editor and search remain functional',Number(await fallback.locator('#statCost').textContent())>0);await fallback.close();
for(const [name,width,height,dpr]of [['desktop',1440,1000,1],['mobile-emulation',390,844,3]]){const perf=await open(b,{viewport:{width,height},deviceScaleFactor:dpr});await perf.locator('#speed').fill('5');await perf.click('#runBtn');await perf.waitForFunction(()=>!isRunning);const data=await perf.evaluate(()=>new Promise(resolve=>{const intervals=[];let t0=performance.now(),last=t0;function tick(now){intervals.push(now-last);last=now;if(now-t0<2200)requestAnimationFrame(tick);else{intervals.shift();intervals.sort((a,b)=>a-b);const gl=atlas3D.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');resolve({fps:1000/(intervals.reduce((a,b)=>a+b,0)/intervals.length),p95:intervals[Math.floor(intervals.length*.95)],calls:atlas3D.renderer.info.render.calls,triangles:atlas3D.renderer.info.render.triangles,gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unavailable'})}}requestAnimationFrame(tick)}));report.performance.push({viewport:name,...data});await perf.close();}
ok('no unexpected browser errors',report.errors.length===0);ok('all resources loaded',report.resources.length===0);
}finally{fs.mkdirSync(path.resolve(__dirname,'../docs/atlas'),{recursive:true});fs.writeFileSync(path.resolve(__dirname,'../docs/atlas/verification.json'),JSON.stringify(report,null,2));await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
